#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Vapolia.WheelPickerDemo.Resource", IsApplication=true)]

namespace Vapolia.WheelPickerDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Vapolia.Resource.Array.days = global::Vapolia.WheelPickerDemo.Resource.Array.days;
			global::Vapolia.Resource.Array.months = global::Vapolia.WheelPickerDemo.Resource.Array.months;
			global::Vapolia.Resource.Array.wheelDefaultItems = global::Vapolia.WheelPickerDemo.Resource.Array.wheelDefaultItems;
			global::Vapolia.Resource.Array.wheelDefaultItems2 = global::Vapolia.WheelPickerDemo.Resource.Array.wheelDefaultItems2;
			global::Vapolia.Resource.Array.years = global::Vapolia.WheelPickerDemo.Resource.Array.years;
			global::Vapolia.Resource.Attribute.enableTrace = global::Vapolia.WheelPickerDemo.Resource.Attribute.enableTrace;
			global::Vapolia.Resource.Attribute.fadingItems = global::Vapolia.WheelPickerDemo.Resource.Attribute.fadingItems;
			global::Vapolia.Resource.Attribute.horizontalSpaceBetweenWheels = global::Vapolia.WheelPickerDemo.Resource.Attribute.horizontalSpaceBetweenWheels;
			global::Vapolia.Resource.Attribute.isCurved = global::Vapolia.WheelPickerDemo.Resource.Attribute.isCurved;
			global::Vapolia.Resource.Attribute.itemAlign = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemAlign;
			global::Vapolia.Resource.Attribute.itemAligns = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemAligns;
			global::Vapolia.Resource.Attribute.itemHeights = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemHeights;
			global::Vapolia.Resource.Attribute.itemTextColor = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemTextColor;
			global::Vapolia.Resource.Attribute.itemTextSize = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemTextSize;
			global::Vapolia.Resource.Attribute.itemWidths = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemWidths;
			global::Vapolia.Resource.Attribute.itemsSource = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemsSource;
			global::Vapolia.Resource.Attribute.selectedItem = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectedItem;
			global::Vapolia.Resource.Attribute.selectedItemTextColor = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectedItemTextColor;
			global::Vapolia.Resource.Attribute.selectionLinesColor = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectionLinesColor;
			global::Vapolia.Resource.Attribute.selectionLinesThickness = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectionLinesThickness;
			global::Vapolia.Resource.Attribute.showSelectionLines = global::Vapolia.WheelPickerDemo.Resource.Attribute.showSelectionLines;
			global::Vapolia.Resource.Attribute.verticalSpaceBetweenItems = global::Vapolia.WheelPickerDemo.Resource.Attribute.verticalSpaceBetweenItems;
			global::Vapolia.Resource.Attribute.visibleItemCount = global::Vapolia.WheelPickerDemo.Resource.Attribute.visibleItemCount;
			global::Vapolia.Resource.Id.center = global::Vapolia.WheelPickerDemo.Resource.Id.center;
			global::Vapolia.Resource.Id.left = global::Vapolia.WheelPickerDemo.Resource.Id.left;
			global::Vapolia.Resource.Id.right = global::Vapolia.WheelPickerDemo.Resource.Id.right;
			global::Vapolia.Resource.Style.WheelPickerStyle = global::Vapolia.WheelPickerDemo.Resource.Style.WheelPickerStyle;
			global::Vapolia.Resource.Styleable.WheelPicker = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker;
			global::Vapolia.Resource.Styleable.WheelPicker_android_gravity = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_android_gravity;
			global::Vapolia.Resource.Styleable.WheelPicker_enableTrace = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_enableTrace;
			global::Vapolia.Resource.Styleable.WheelPicker_fadingItems = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_fadingItems;
			global::Vapolia.Resource.Styleable.WheelPicker_horizontalSpaceBetweenWheels = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_horizontalSpaceBetweenWheels;
			global::Vapolia.Resource.Styleable.WheelPicker_isCurved = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_isCurved;
			global::Vapolia.Resource.Styleable.WheelPicker_itemAlign = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemAlign;
			global::Vapolia.Resource.Styleable.WheelPicker_itemAligns = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemAligns;
			global::Vapolia.Resource.Styleable.WheelPicker_itemHeights = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemHeights;
			global::Vapolia.Resource.Styleable.WheelPicker_itemTextColor = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemTextColor;
			global::Vapolia.Resource.Styleable.WheelPicker_itemTextSize = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemTextSize;
			global::Vapolia.Resource.Styleable.WheelPicker_itemWidths = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemWidths;
			global::Vapolia.Resource.Styleable.WheelPicker_itemsSource = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemsSource;
			global::Vapolia.Resource.Styleable.WheelPicker_selectedItem = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectedItem;
			global::Vapolia.Resource.Styleable.WheelPicker_selectedItemTextColor = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectedItemTextColor;
			global::Vapolia.Resource.Styleable.WheelPicker_selectionLinesColor = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectionLinesColor;
			global::Vapolia.Resource.Styleable.WheelPicker_selectionLinesThickness = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectionLinesThickness;
			global::Vapolia.Resource.Styleable.WheelPicker_showSelectionLines = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_showSelectionLines;
			global::Vapolia.Resource.Styleable.WheelPicker_verticalSpaceBetweenItems = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_verticalSpaceBetweenItems;
			global::Vapolia.Resource.Styleable.WheelPicker_visibleItemCount = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_visibleItemCount;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040001
			public const int days = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int months = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int wheelDefaultItems = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int wheelDefaultItems2 = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int years = 2130968579;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int enableTrace = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int fadingItems = 2130771979;
			
			// aapt resource value: 0x7f010004
			public const int horizontalSpaceBetweenWheels = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int isCurved = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int itemAlign = 2130771978;
			
			// aapt resource value: 0x7f010010
			public const int itemAligns = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int itemHeights = 2130771985;
			
			// aapt resource value: 0x7f010007
			public const int itemTextColor = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int itemTextSize = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int itemWidths = 2130771983;
			
			// aapt resource value: 0x7f010001
			public const int itemsSource = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int selectedItem = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int selectedItemTextColor = 2130771976;
			
			// aapt resource value: 0x7f01000d
			public const int selectionLinesColor = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int selectionLinesThickness = 2130771982;
			
			// aapt resource value: 0x7f01000c
			public const int showSelectionLines = 2130771980;
			
			// aapt resource value: 0x7f010005
			public const int verticalSpaceBetweenItems = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int visibleItemCount = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int center = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int left = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int right = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int valueText = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int valueText2 = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int wheelView = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int WheelPickerStyle = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] WheelPicker = new int[] {
					16842927,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int WheelPicker_android_gravity = 0;
			
			// aapt resource value: 1
			public const int WheelPicker_enableTrace = 1;
			
			// aapt resource value: 12
			public const int WheelPicker_fadingItems = 12;
			
			// aapt resource value: 5
			public const int WheelPicker_horizontalSpaceBetweenWheels = 5;
			
			// aapt resource value: 7
			public const int WheelPicker_isCurved = 7;
			
			// aapt resource value: 11
			public const int WheelPicker_itemAlign = 11;
			
			// aapt resource value: 17
			public const int WheelPicker_itemAligns = 17;
			
			// aapt resource value: 18
			public const int WheelPicker_itemHeights = 18;
			
			// aapt resource value: 8
			public const int WheelPicker_itemTextColor = 8;
			
			// aapt resource value: 10
			public const int WheelPicker_itemTextSize = 10;
			
			// aapt resource value: 16
			public const int WheelPicker_itemWidths = 16;
			
			// aapt resource value: 2
			public const int WheelPicker_itemsSource = 2;
			
			// aapt resource value: 3
			public const int WheelPicker_selectedItem = 3;
			
			// aapt resource value: 9
			public const int WheelPicker_selectedItemTextColor = 9;
			
			// aapt resource value: 14
			public const int WheelPicker_selectionLinesColor = 14;
			
			// aapt resource value: 15
			public const int WheelPicker_selectionLinesThickness = 15;
			
			// aapt resource value: 13
			public const int WheelPicker_showSelectionLines = 13;
			
			// aapt resource value: 6
			public const int WheelPicker_verticalSpaceBetweenItems = 6;
			
			// aapt resource value: 4
			public const int WheelPicker_visibleItemCount = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
