#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Vapolia.WheelPickerDemo.Resource", IsApplication=true)]

namespace Vapolia.WheelPickerDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Vapolia.WheelPickerCore.Resource.Array.days = global::Vapolia.WheelPickerDemo.Resource.Array.days;
			global::Vapolia.WheelPickerCore.Resource.Array.months = global::Vapolia.WheelPickerDemo.Resource.Array.months;
			global::Vapolia.WheelPickerCore.Resource.Array.wheelDefaultItems = global::Vapolia.WheelPickerDemo.Resource.Array.wheelDefaultItems;
			global::Vapolia.WheelPickerCore.Resource.Array.wheelDefaultItems2 = global::Vapolia.WheelPickerDemo.Resource.Array.wheelDefaultItems2;
			global::Vapolia.WheelPickerCore.Resource.Array.years = global::Vapolia.WheelPickerDemo.Resource.Array.years;
			global::Vapolia.WheelPickerCore.Resource.Attribute.enableTrace = global::Vapolia.WheelPickerDemo.Resource.Attribute.enableTrace;
			global::Vapolia.WheelPickerCore.Resource.Attribute.fadingItems = global::Vapolia.WheelPickerDemo.Resource.Attribute.fadingItems;
			global::Vapolia.WheelPickerCore.Resource.Attribute.horizontalSpaceBetweenWheels = global::Vapolia.WheelPickerDemo.Resource.Attribute.horizontalSpaceBetweenWheels;
			global::Vapolia.WheelPickerCore.Resource.Attribute.isCurved = global::Vapolia.WheelPickerDemo.Resource.Attribute.isCurved;
			global::Vapolia.WheelPickerCore.Resource.Attribute.itemAlign = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemAlign;
			global::Vapolia.WheelPickerCore.Resource.Attribute.itemAligns = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemAligns;
			global::Vapolia.WheelPickerCore.Resource.Attribute.itemHeights = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemHeights;
			global::Vapolia.WheelPickerCore.Resource.Attribute.itemsSource = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemsSource;
			global::Vapolia.WheelPickerCore.Resource.Attribute.itemTextSize = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemTextSize;
			global::Vapolia.WheelPickerCore.Resource.Attribute.itemWidths = global::Vapolia.WheelPickerDemo.Resource.Attribute.itemWidths;
			global::Vapolia.WheelPickerCore.Resource.Attribute.selectedItem = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectedItem;
			global::Vapolia.WheelPickerCore.Resource.Attribute.selectedItemTextColor = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectedItemTextColor;
			global::Vapolia.WheelPickerCore.Resource.Attribute.selectionLinesColor = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectionLinesColor;
			global::Vapolia.WheelPickerCore.Resource.Attribute.selectionLinesThickness = global::Vapolia.WheelPickerDemo.Resource.Attribute.selectionLinesThickness;
			global::Vapolia.WheelPickerCore.Resource.Attribute.showSelectionLines = global::Vapolia.WheelPickerDemo.Resource.Attribute.showSelectionLines;
			global::Vapolia.WheelPickerCore.Resource.Attribute.verticalSpaceBetweenItems = global::Vapolia.WheelPickerDemo.Resource.Attribute.verticalSpaceBetweenItems;
			global::Vapolia.WheelPickerCore.Resource.Attribute.visibleItemCount = global::Vapolia.WheelPickerDemo.Resource.Attribute.visibleItemCount;
			global::Vapolia.WheelPickerCore.Resource.Attribute.wp_itemTextColor = global::Vapolia.WheelPickerDemo.Resource.Attribute.wp_itemTextColor;
			global::Vapolia.WheelPickerCore.Resource.Id.center = global::Vapolia.WheelPickerDemo.Resource.Id.center;
			global::Vapolia.WheelPickerCore.Resource.Id.left = global::Vapolia.WheelPickerDemo.Resource.Id.left;
			global::Vapolia.WheelPickerCore.Resource.Id.right = global::Vapolia.WheelPickerDemo.Resource.Id.right;
			global::Vapolia.WheelPickerCore.Resource.Style.WheelPickerStyle = global::Vapolia.WheelPickerDemo.Resource.Style.WheelPickerStyle;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_android_gravity = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_android_gravity;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_enableTrace = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_enableTrace;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_fadingItems = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_fadingItems;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_horizontalSpaceBetweenWheels = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_horizontalSpaceBetweenWheels;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_isCurved = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_isCurved;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_itemAlign = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemAlign;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_itemAligns = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemAligns;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_itemHeights = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemHeights;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_itemsSource = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemsSource;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_itemTextSize = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemTextSize;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_itemWidths = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_itemWidths;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_selectedItem = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectedItem;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_selectedItemTextColor = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectedItemTextColor;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_selectionLinesColor = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectionLinesColor;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_selectionLinesThickness = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_selectionLinesThickness;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_showSelectionLines = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_showSelectionLines;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_verticalSpaceBetweenItems = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_verticalSpaceBetweenItems;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_visibleItemCount = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_visibleItemCount;
			global::Vapolia.WheelPickerCore.Resource.Styleable.WheelPicker_wp_itemTextColor = global::Vapolia.WheelPickerDemo.Resource.Styleable.WheelPicker_wp_itemTextColor;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int days = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int months = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int wheelDefaultItems = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int wheelDefaultItems2 = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int years = 2130771972;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int enableTrace = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int fadingItems = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int horizontalSpaceBetweenWheels = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int isCurved = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int itemAlign = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int itemAligns = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int itemHeights = 2130837510;
			
			// aapt resource value: 0x7F020009
			public const int itemsSource = 2130837513;
			
			// aapt resource value: 0x7F020007
			public const int itemTextSize = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int itemWidths = 2130837512;
			
			// aapt resource value: 0x7F02000A
			public const int selectedItem = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int selectedItemTextColor = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int selectionLinesColor = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int selectionLinesThickness = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int showSelectionLines = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int verticalSpaceBetweenItems = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int visibleItemCount = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int wp_itemTextColor = 2130837521;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int center = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int left = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int right = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int valueText = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int valueText2 = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int wheelView = 2130968581;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int Main = 2131034112;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int WheelPickerStyle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10100AF,0x7F020000,0x7F020001,0x7F020002,0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007,0x7F020008,0x7F020009,0x7F02000A,0x7F02000B,0x7F02000C,0x7F02000D,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011 }
			public static int[] WheelPicker = new int[] {
					16842927,
					2130837504,
					2130837505,
					2130837506,
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511,
					2130837512,
					2130837513,
					2130837514,
					2130837515,
					2130837516,
					2130837517,
					2130837518,
					2130837519,
					2130837520,
					2130837521};
			
			// aapt resource value: 0
			public const int WheelPicker_android_gravity = 0;
			
			// aapt resource value: 1
			public const int WheelPicker_enableTrace = 1;
			
			// aapt resource value: 2
			public const int WheelPicker_fadingItems = 2;
			
			// aapt resource value: 3
			public const int WheelPicker_horizontalSpaceBetweenWheels = 3;
			
			// aapt resource value: 4
			public const int WheelPicker_isCurved = 4;
			
			// aapt resource value: 5
			public const int WheelPicker_itemAlign = 5;
			
			// aapt resource value: 6
			public const int WheelPicker_itemAligns = 6;
			
			// aapt resource value: 7
			public const int WheelPicker_itemHeights = 7;
			
			// aapt resource value: 10
			public const int WheelPicker_itemsSource = 10;
			
			// aapt resource value: 8
			public const int WheelPicker_itemTextSize = 8;
			
			// aapt resource value: 9
			public const int WheelPicker_itemWidths = 9;
			
			// aapt resource value: 11
			public const int WheelPicker_selectedItem = 11;
			
			// aapt resource value: 12
			public const int WheelPicker_selectedItemTextColor = 12;
			
			// aapt resource value: 13
			public const int WheelPicker_selectionLinesColor = 13;
			
			// aapt resource value: 14
			public const int WheelPicker_selectionLinesThickness = 14;
			
			// aapt resource value: 15
			public const int WheelPicker_showSelectionLines = 15;
			
			// aapt resource value: 16
			public const int WheelPicker_verticalSpaceBetweenItems = 16;
			
			// aapt resource value: 17
			public const int WheelPicker_visibleItemCount = 17;
			
			// aapt resource value: 18
			public const int WheelPicker_wp_itemTextColor = 18;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
