using Microsoft.Extensions.Logging;
using Vapolia.Svgs;
using Vapolia.WheelPickers;

namespace WheelPickerMauiDemo;

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            })
            .UseWheelPicker("eyJhbGciOiJSUzI1NiIsImtpZCI6InZhcG9saWFzaWciLCJ0eXAiOiJKV1QifQ.eyJodHRwczovL3NjaGVtYXMudmFwb2xpYS5ldS8yMDIwLzA1L2NsYWltcy9MaWNlbnNlc0NsYWltIjoie1wiTGljZW5zZXNcIjpbe1wiUHJvZHVjdFwiOlwid2hlZWxwaWNrZXJcIixcIk9zXCI6XCJpb3NcIixcIkFwcElkXCI6XCJldS52YXBvbGlhLndoZWVscGlja2VybWF1aWRlbW9cIixcIk1heEJ1aWxkXCI6XCIyMDM1LTA5LTA4VDAwOjAwOjAwKzAwOjAwXCJ9LHtcIlByb2R1Y3RcIjpcIndoZWVscGlja2VyXCIsXCJPc1wiOlwiYW5kcm9pZFwiLFwiQXBwSWRcIjpcImV1LnZhcG9saWEud2hlZWxwaWNrZXJtYXVpZGVtb1wiLFwiTWF4QnVpbGRcIjpcIjIwMzUtMDktMDhUMDA6MDA6MDArMDA6MDBcIn0se1wiUHJvZHVjdFwiOlwic3ZnXCIsXCJPc1wiOlwiaW9zXCIsXCJBcHBJZFwiOlwiZXUudmFwb2xpYS53aGVlbHBpY2tlcm1hdWlkZW1vXCIsXCJNYXhCdWlsZFwiOlwiMjAzNS0wOS0wOFQwMDowMDowMCswMDowMFwifSx7XCJQcm9kdWN0XCI6XCJzdmdcIixcIk9zXCI6XCJhbmRyb2lkXCIsXCJBcHBJZFwiOlwiZXUudmFwb2xpYS53aGVlbHBpY2tlcm1hdWlkZW1vXCIsXCJNYXhCdWlsZFwiOlwiMjAzNS0wOS0wOFQwMDowMDowMCswMDowMFwifSx7XCJQcm9kdWN0XCI6XCJzdmdcIixcIk9zXCI6XCJ3aW5kb3dzXCIsXCJBcHBJZFwiOlwiZXUudmFwb2xpYS53aGVlbHBpY2tlcm1hdWlkZW1vXCIsXCJNYXhCdWlsZFwiOlwiMjAzNS0wOS0wOFQwMDowMDowMCswMDowMFwifV19IiwibmJmIjoxNzU3MzU4NDgwLCJleHAiOjIzODg0NDE2MDAsImlhdCI6MTc1NzM1ODQ4MCwiaXNzIjoiaHR0cHM6Ly92YXBvbGlhLmV1L2F1dGhvcml0eSIsImF1ZCI6Imh0dHBzOi8vdmFwb2xpYS5ldS9hdXRob3JpdHkvbGljZW5zZXMifQ.cbiGL7RmmJB2P-HO1MzTR_NOJiKjSJpApiVgmv0ZljRNF6BrZDuHMTK6wq7ptpCxNN8sbOGCT21KjEMJQCnijws69ccQ08tDrloYMmBXHEbJglfE8WGbv6cszawse9bVBqcpwPO8gQ2VKaPDbizOmuGIapE62SHzY4lRyez2_mBO69IWZVdyQ8c7ZBjY5SMVEYDzLSrg-64bqanRpP_PtmbiBs-q5JB7mDt1a_bstOqer8E7v9ZvBmW-gPUU7qA244MZ1josRfKn3rcFmW8gG_NnIM2j3XBsAdetJcRYMFf48Fbu2m7KMX5FlisEUFOW1B6kIkOahZqEK6dcdC6JJA")
            .UseEasySvg("eyJhbGciOiJSUzI1NiIsImtpZCI6InZhcG9saWFzaWciLCJ0eXAiOiJKV1QifQ.eyJodHRwczovL3NjaGVtYXMudmFwb2xpYS5ldS8yMDIwLzA1L2NsYWltcy9MaWNlbnNlc0NsYWltIjoie1wiTGljZW5zZXNcIjpbe1wiUHJvZHVjdFwiOlwid2hlZWxwaWNrZXJcIixcIk9zXCI6XCJpb3NcIixcIkFwcElkXCI6XCJldS52YXBvbGlhLndoZWVscGlja2VybWF1aWRlbW9cIixcIk1heEJ1aWxkXCI6XCIyMDM1LTA5LTA4VDAwOjAwOjAwKzAwOjAwXCJ9LHtcIlByb2R1Y3RcIjpcIndoZWVscGlja2VyXCIsXCJPc1wiOlwiYW5kcm9pZFwiLFwiQXBwSWRcIjpcImV1LnZhcG9saWEud2hlZWxwaWNrZXJtYXVpZGVtb1wiLFwiTWF4QnVpbGRcIjpcIjIwMzUtMDktMDhUMDA6MDA6MDArMDA6MDBcIn0se1wiUHJvZHVjdFwiOlwic3ZnXCIsXCJPc1wiOlwiaW9zXCIsXCJBcHBJZFwiOlwiZXUudmFwb2xpYS53aGVlbHBpY2tlcm1hdWlkZW1vXCIsXCJNYXhCdWlsZFwiOlwiMjAzNS0wOS0wOFQwMDowMDowMCswMDowMFwifSx7XCJQcm9kdWN0XCI6XCJzdmdcIixcIk9zXCI6XCJhbmRyb2lkXCIsXCJBcHBJZFwiOlwiZXUudmFwb2xpYS53aGVlbHBpY2tlcm1hdWlkZW1vXCIsXCJNYXhCdWlsZFwiOlwiMjAzNS0wOS0wOFQwMDowMDowMCswMDowMFwifSx7XCJQcm9kdWN0XCI6XCJzdmdcIixcIk9zXCI6XCJ3aW5kb3dzXCIsXCJBcHBJZFwiOlwiZXUudmFwb2xpYS53aGVlbHBpY2tlcm1hdWlkZW1vXCIsXCJNYXhCdWlsZFwiOlwiMjAzNS0wOS0wOFQwMDowMDowMCswMDowMFwifV19IiwibmJmIjoxNzU3MzU4NDgwLCJleHAiOjIzODg0NDE2MDAsImlhdCI6MTc1NzM1ODQ4MCwiaXNzIjoiaHR0cHM6Ly92YXBvbGlhLmV1L2F1dGhvcml0eSIsImF1ZCI6Imh0dHBzOi8vdmFwb2xpYS5ldS9hdXRob3JpdHkvbGljZW5zZXMifQ.cbiGL7RmmJB2P-HO1MzTR_NOJiKjSJpApiVgmv0ZljRNF6BrZDuHMTK6wq7ptpCxNN8sbOGCT21KjEMJQCnijws69ccQ08tDrloYMmBXHEbJglfE8WGbv6cszawse9bVBqcpwPO8gQ2VKaPDbizOmuGIapE62SHzY4lRyez2_mBO69IWZVdyQ8c7ZBjY5SMVEYDzLSrg-64bqanRpP_PtmbiBs-q5JB7mDt1a_bstOqer8E7v9ZvBmW-gPUU7qA244MZ1josRfKn3rcFmW8gG_NnIM2j3XBsAdetJcRYMFf48Fbu2m7KMX5FlisEUFOW1B6kIkOahZqEK6dcdC6JJA")
            ;

#if DEBUG
        builder.Logging.AddDebug();
#endif

        return builder.Build();
    }
}